criando novo tema e adicionando página em construção
PHPediaBR/plataforma pull request #2
Opened 2023-06-05 16:37 UTC by patriciomartinns

Foi criado um novo tema e modificado o arquivo base.html.twig para a criação da página "Em construção".

2023-06-05 17:30 UTC, WendellAdriel requested changes

2023-06-05 17:30 UTC, WendellAdriel commented on config.php
Esse arquivo não deveria estar com configs para o projeto, tipo mudar o nome, autor, descrição, os links das redes sociais, etc?

2023-06-05 17:33 UTC, patriciomartinns commented on config.php
Acho que não porque será removido após a construção da plataforma.

2023-06-05 18:16 UTC, erikaheidi approved these changes, later dismissed

2023-06-05 18:16 UTC, erikaheidi commented on config.php
> +        'Twitter' => envconfig('LINK_TWITTER'),
```suggestion
        'Twitter' => envconfig('LINK_TWITTER', 'https://twitter.com/phpediabr'),
```

2023-06-05 18:16 UTC, erikaheidi commented on config.php
> +        'Github'  => envconfig('LINK_GITHUB', 'https://github.com/minicli/librarian'),
```suggestion
        'Github'  => envconfig('LINK_GITHUB', 'https://github.com/PHPediaBR/plataforma'),
```

2023-06-06 09:24 UTC, WendellAdriel approved these changes

2023-06-06 09:25 UTC, WendellAdriel commented
@patriciomartinns muito obrigado!!! 💪

2023-06-06 09:25 UTC, merged